/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessModelRouteImport } from './routes/business-model'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as InvestmentApproachRouteImport } from './routes/investment-approach'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ResponsibleOwnershipRouteImport } from './routes/responsible-ownership'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessModelRoute = BusinessModelRouteImport.update({
  id: '/business-model',
  path: '/business-model',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentApproachRoute = InvestmentApproachRouteImport.update({
  id: '/investment-approach',
  path: '/investment-approach',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleOwnershipRoute = ResponsibleOwnershipRouteImport.update({
  id: '/responsible-ownership',
  path: '/responsible-ownership',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/contact': typeof ContactRoute
  '/investment-approach': typeof InvestmentApproachRoute
  '/partners': typeof PartnersRoute
  '/responsible-ownership': typeof ResponsibleOwnershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/contact': typeof ContactRoute
  '/investment-approach': typeof InvestmentApproachRoute
  '/partners': typeof PartnersRoute
  '/responsible-ownership': typeof ResponsibleOwnershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-model': typeof BusinessModelRoute
  '/contact': typeof ContactRoute
  '/investment-approach': typeof InvestmentApproachRoute
  '/partners': typeof PartnersRoute
  '/responsible-ownership': typeof ResponsibleOwnershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-model'
    | '/contact'
    | '/investment-approach'
    | '/partners'
    | '/responsible-ownership'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-model'
    | '/contact'
    | '/investment-approach'
    | '/partners'
    | '/responsible-ownership'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-model'
    | '/contact'
    | '/investment-approach'
    | '/partners'
    | '/responsible-ownership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessModelRoute: typeof BusinessModelRoute
  ContactRoute: typeof ContactRoute
  InvestmentApproachRoute: typeof InvestmentApproachRoute
  PartnersRoute: typeof PartnersRoute
  ResponsibleOwnershipRoute: typeof ResponsibleOwnershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-model': {
      id: '/business-model'
      path: '/business-model'
      fullPath: '/business-model'
      preLoaderRoute: typeof BusinessModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-approach': {
      id: '/investment-approach'
      path: '/investment-approach'
      fullPath: '/investment-approach'
      preLoaderRoute: typeof InvestmentApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-ownership': {
      id: '/responsible-ownership'
      path: '/responsible-ownership'
      fullPath: '/responsible-ownership'
      preLoaderRoute: typeof ResponsibleOwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessModelRoute: BusinessModelRoute,
  ContactRoute: ContactRoute,
  InvestmentApproachRoute: InvestmentApproachRoute,
  PartnersRoute: PartnersRoute,
  ResponsibleOwnershipRoute: ResponsibleOwnershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
